version: '3.1'
services:
    mysql:
        image: mysql
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: "123456"
        restart: always
        ports:
            - "3306:3306"